name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add remote using secret token from GitHub Secrets
          git remote remove huggingface || true
          git remote add huggingface https://Oxyraptor:$HF_TOKEN@huggingface.co/spaces/Oxyraptor/Heat-sink-backend
          git push --force huggingface main
